################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_JANSSON "jansson")
    if (PC_JANSSON_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_JANSSON_CFLAGS} ${PC_JANSSON_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_JANSSON_INCLUDE_HINTS ${PC_JANSSON_INCLUDE_DIRS} ${PC_JANSSON_INCLUDE_DIRS}/*)
        set(PC_JANSSON_LIBRARY_HINTS ${PC_JANSSON_LIBRARY_DIRS} ${PC_JANSSON_LIBRARY_DIRS}/*)
    endif(PC_JANSSON_FOUND)
endif (NOT MSVC)

find_path (
    JANSSON_INCLUDE_DIRS
    NAMES jansson.h
    HINTS ${PC_JANSSON_INCLUDE_HINTS}
)

find_library (
    JANSSON_LIBRARIES
    NAMES jansson
    HINTS ${PC_JANSSON_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    JANSSON
    REQUIRED_VARS JANSSON_LIBRARIES JANSSON_INCLUDE_DIRS
)
mark_as_advanced(
    JANSSON_FOUND
    JANSSON_LIBRARIES JANSSON_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
