/*  =========================================================================
    mql_server - mqless Server

    ** WARNING *************************************************************
    THIS SOURCE FILE IS 100% GENERATED. If you edit this file, you will lose
    your changes at the next build cycle. This is great for temporary printf
    statements. DO NOT MAKE ANY CHANGES YOU WISH TO KEEP. The correct places
    for commits are:

     * The XML model used for this code generation: mql_server.xml, or
     * The code generation script that built this file: zproto_server_c
    ************************************************************************
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef MQL_SERVER_H_INCLUDED
#define MQL_SERVER_H_INCLUDED

#include <czmq.h>

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/mql_server.api" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef MQL_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Create a new mql_server, return the reference if successful,
//  or NULL if construction failed due to lack of available memory.
MQL_EXPORT mql_server_t *
    mql_server_new (zconfig_t *config);

//  *** Draft method, for development use, may change without warning ***
//  Destroy the mql_server and free all memory used by the object.
MQL_EXPORT void
    mql_server_destroy (mql_server_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
MQL_EXPORT void
    mql_server_test (bool verbose);

#endif // MQL_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
