/*  =========================================================================
    mql_classes - private header file

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef MQL_CLASSES_H_INCLUDED
#define MQL_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/mqless.h"

//  Extra headers

//  Opaque class structures to allow forward references
#ifndef AWS_T_DEFINED
typedef struct _aws_t aws_t;
#define AWS_T_DEFINED
#endif
#ifndef AWS_SIGN_T_DEFINED
typedef struct _aws_sign_t aws_sign_t;
#define AWS_SIGN_T_DEFINED
#endif
#ifndef MAILBOX_T_DEFINED
typedef struct _mailbox_t mailbox_t;
#define MAILBOX_T_DEFINED
#endif

//  Internal API

#include "aws.h"
#include "aws_sign.h"
#include "mailbox.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef MQL_BUILD_DRAFT_API

//  Self test for private classes
MQL_PRIVATE void
    mql_private_selftest (bool verbose, const char *subtest);

#endif // MQL_BUILD_DRAFT_API

#endif
